const constants	= {
	LOGIN_USER: "LOGIN_USER",
	LOGIN_USER_RESULT: "LOGIN_USER_RESULT",
	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",
	FETCH_PRODUCT_DETAILS: "FETCH_PRODUCT_DETAILS",
	CANCEL_FETCH_PRODUCT_DETAILS: "CANCEL_FETCH_PRODUCT_DETAILS",
	
	CANCEL_LOGIN_USER: "CANCEL_LOGIN_USER",
	SIGN_UP_USER: "SIGN_UP_USER",
	CANCEL_SIGN_UP_USER: "CANCEL_SIGN_UP_USER",
	FETCH_RETAILER_DETAILS: "FETCH_RETAILER_DETAILS",
	CANCEL_FETCH_RETAILER_DETAILS: "CANEL_FETCH_RETAILER_DETAILS",
	FETCH_REDEEM_POINTS_VENDOR: "FETCH_REDEEM_POINTS_VENDOR",
	CANCEL_FETCH_REDEEM_POINTS_VENDOR: "CANCEL_FETCH_REDEEM_POINTS_VENDOR",
	SAVE_RETAILER_DETAILS: "SAVE_RETAILER_DETAILS",
	CANCEL_SAVE_RETAILER_DETAILS: "CANCEL_SAVE_RETAILER_DETAILS",
	REQUEST_CHECK_AUTHENTIC_REMOTE: "REQUEST_CHECK_AUTHENTIC_REMOTE",
	CANCEL_REQUEST_CHECK_AUTHENTIC_REMOTE: "CANCEL_REQUEST_CHECK_AUTHENTIC_REMOTE",
}

export default constants